name = "sborrbot-worker"
main = "src/index.ts"
compatibility_date = "2025-02-01"

[[d1_databases]]
binding = "DB"
database_name = "sborrbot-db"
database_id = "7ae5a815-7c5d-49f7-8888-4cae06ebb600"
migrations_dir = "../migrations"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "sborrbot-media"

[vars]
BOT_SECRET = "change-me-in-production"
# BOT_TOKEN â†’ wrangler secret put BOT_TOKEN
